apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

helmCharts:
- name: gatekeeper
  namespace: gatekeeper-system
  includeCRDs: true
  valuesInline:
    postInstall:
      labelNamespace:
        enabled: false
    upgradeCRDs:
      enabled: false
    enableDeleteOperations: true
  releaseName: gatekeeper
  repo: https://open-policy-agent.github.io/gatekeeper/charts
  version: 3.17.1

resources:
- namespace.yaml
- constraints.yaml
- sync-sets.yaml
