apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: capi-system

helmCharts:
- name: cluster-api-operator
  namespace: capi-system
  includeCRDs: true
  valuesInline:
    installCRDs: true
    infrastructure: vcluster:v0.2.0
    configSecret:
      name: capi-credentials
      namespace: capi-system
  releaseName: capi
  repo: https://kubernetes-sigs.github.io/cluster-api-operator
  version: 0.14.0

resources:
- credentials-secret.yaml
