services:
  minio:
    image: quay.io/minio/minio:${MINIO_TAG}
    command:
    - server
    - /datacurl
    - --console-address
    - ":9001"
    environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
    - proxy
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
    - minio:/data

volumes:
  minio:

networks: 
  proxy:
    name: proxy
