apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: cert-manager

helmCharts:
- name: cert-manager
  namespace: cert-manager
  includeCRDs: true
  valuesInline:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  version: 1.16.1

resources:
- namespace.yaml
